# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tttest001',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tttest001',
                'lib_path': 'tttest001'},
  'syms': {'tttest001.core': {'tttest001.core.foo': ('core.html#foo', 'tttest001/core.py')}}}
